# Generated by Django 4.2.1 on 2023-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('employee', models.CharField(max_length=30)),
            ],
        ),
    ]
