# Generated by Django 4.2.1 on 2023-05-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('programari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezervareServicii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('completed', 'completed')], max_length=9)),
                ('date', models.DateTimeField()),
                ('id_angajat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('id_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programari.service')),
            ],
        ),
    ]
