# Generated by Django 4.2.1 on 2023-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0003_alter_rezervareservicii_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervareservicii',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('completed', 'completed')], default='draft', max_length=9),
        ),
    ]
