# Generated by Django 4.2.1 on 2023-05-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('tip_produs', models.CharField(choices=[('1', 'Ingrijire par'), ('2', 'Ingrijire barba'), ('3', 'Accesorii')], max_length=20)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producttype')),
            ],
        ),
    ]
