# Generated by Django 4.2.1 on 2023-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_accesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('tip_produs', models.CharField(choices=[('1', 'Ingrijire par'), ('2', 'Ingrijire barba'), ('3', 'Accesorii')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
