# Generated by Django 4.2.1 on 2023-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_produs', models.IntegerField()),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
