# Generated by Django 4.2.1 on 2023-05-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_id_produs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_produs',
            new_name='produs',
        ),
    ]
